# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Rebuild CLI JAR file
on:
  pull_request:
    branches:
      - master
jobs:
  build-and-commit-cli-jar:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.AUTOMATION_REPO_ACCESS_TOKEN }}

      - name: Build JAR
        run: |
          mvn clean package -DskipTests

      - name: Copy JAR to root directory
        run: |
          cp -f modules/swagger-codegen-cli/target/swagger-codegen-cli.jar .

      - name: Commit updated connectors (if needed)
        if: github.actor != 'scoffableautomation' # If this run was already triggered by an automated commit, this avoids a potential infinite loop
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Regenerated Swagger CLI
